export const env = {
  HOODPAY_API_KEY: process.env.HOODPAY_API_KEY,
  HOODPAY_API_URL: process.env.HOODPAY_API_URL,
  HOODPAY_BUSINESS_ID: process.env.HOODPAY_BUSINESS_ID,
  HOODPAY_STORE_ID:
    process.env.HOODPAY_STORE_ID ?? process.env.HOODPAY_BUSINESS_ID,
  HOODPAY_WEBHOOK_SECRET: process.env.HOODPAY_WEBHOOK_SECRET,
  SUPABASE_SERVICE_ROLE_KEY: process.env.SUPABASE_SERVICE_ROLE_KEY,
  SERPAPI_API_KEY: process.env.SERPAPI_API_KEY!,
  SERPAPI_DEBUG: process.env.SERPAPI_DEBUG === 'true',
  BASE_URL: process.env.BASE_URL,
  CHECKOUT_SUCCESS_URL: process.env.CHECKOUT_SUCCESS_URL,
  CHECKOUT_CANCEL_URL: process.env.CHECKOUT_CANCEL_URL,
  NODE_ENV: process.env.NODE_ENV,
  NEXT_PUBLIC_ENABLE_HOODPAY: process.env.NEXT_PUBLIC_ENABLE_HOODPAY === 'true',
  NEXT_PUBLIC_BASE_URL:
    process.env.NEXT_PUBLIC_BASE_URL ?? 'http://localhost:3000',
  NEXT_PUBLIC_APP_NAME: process.env.NEXT_PUBLIC_APP_NAME ?? 'App',
  NEXT_PUBLIC_GOOGLE_SITE_VERIFICATION:
    process.env.NEXT_PUBLIC_GOOGLE_SITE_VERIFICATION,
  NEXT_PUBLIC_ENABLE_WEB_PAYMENT_API: false,
  NEXT_PUBLIC_SUPABASE_URL: process.env.NEXT_PUBLIC_SUPABASE_URL,
  NEXT_PUBLIC_SUPABASE_PUBLISHABLE_DEFAULT_KEY:
    process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_DEFAULT_KEY,
} as const;
